// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportWorld.Data;

namespace SportWorld.Migrations
{
    [DbContext(typeof(SportWorldContext))]
    partial class SportWorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportWorld.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ProductID");

                    b.Property<string>("PublisherUserName");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PublisherUserName");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SportWorld.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SportWorld.Models.Store", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClosingHour");

                    b.Property<double>("Latitude");

                    b.Property<double>("Lontitude");

                    b.Property<string>("Name");

                    b.Property<string>("OpeningHour");

                    b.HasKey("ID");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("SportWorld.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("Gender");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Password");

                    b.HasKey("UserName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SportWorld.Models.Comment", b =>
                {
                    b.HasOne("SportWorld.Models.Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductID");

                    b.HasOne("SportWorld.Models.User", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherUserName");
                });
#pragma warning restore 612, 618
        }
    }
}
